import 'package:flutter/material.dart';
import '../../data/models/platform_model.dart';

class PlatformConstants {
  static const List<PlatformModel> platforms = [
    PlatformModel(
      name: 'YouTube',
      url: 'https://m.youtube.com',
      icon: Icons.play_circle_filled,
      iconColor: Color(0xFFFF0000),
      category: 'video',
      backgroundColor: Color(0xFFFF0000),
    ),
    PlatformModel(
      name: 'Music',
      url: 'https://music.youtube.com',
      icon: Icons.music_note,
      iconColor: Color(0xFFFF0000),
      category: 'music',
      backgroundColor: Color(0xFFFF4444),
    ),
    PlatformModel(
      name: 'Twitch',
      url: 'https://m.twitch.tv',
      icon: Icons.videocam,
      iconColor: Color(0xFF9146FF),
      category: 'video',
      backgroundColor: Color(0xFF9146FF),
    ),
    PlatformModel(
      name: 'Rumble',
      url: 'https://rumble.com',
      icon: Icons.video_library,
      iconColor: Color(0xFF85C742),
      category: 'video',
      backgroundColor: Color(0xFF85C742),
    ),
    PlatformModel(
      name: 'Duolingo',
      url: 'https://duolingo.com',
      icon: Icons.school,
      iconColor: Color(0xFF58CC02),
      category: 'education',
      backgroundColor: Color(0xFF58CC02),
    ),
    PlatformModel(
      name: 'Busuu',
      url: 'https://busuu.com',
      icon: Icons.translate,
      iconColor: Color(0xFF5B5BDB),
      category: 'education',
      backgroundColor: Color(0xFF5B5BDB),
    ),
    PlatformModel(
      name: 'Babbel',
      url: 'https://babbel.com',
      icon: Icons.language,
      iconColor: Color(0xFFD91A46),
      category: 'education',
      backgroundColor: Color(0xFFD91A46),
    ),
    PlatformModel(
      name: 'Memrise',
      url: 'https://memrise.com',
      icon: Icons.psychology,
      iconColor: Color(0xFF00C1C1),
      category: 'education',
      backgroundColor: Color(0xFF00C1C1),
    ),
    PlatformModel(
      name: 'Mondly',
      url: 'https://mondly.com',
      icon: Icons.record_voice_over,
      iconColor: Color(0xFF0072CE),
      category: 'education',
      backgroundColor: Color(0xFF0072CE),
    ),
    PlatformModel(
      name: 'Instagram',
      url: 'https://instagram.com',
      icon: Icons.camera_alt,
      iconColor: Color(0xFFE4405F),
      category: 'social',
      backgroundColor: Color(0xFFE4405F),
    ),
    PlatformModel(
      name: 'Reddit',
      url: 'https://reddit.com',
      icon: Icons.forum,
      iconColor: Color(0xFFFF4500),
      category: 'social',
      backgroundColor: Color(0xFFFF4500),
    ),
    PlatformModel(
      name: 'Facebook',
      url: 'https://facebook.com',
      icon: Icons.facebook,
      iconColor: Color(0xFF1877F2),
      category: 'social',
      backgroundColor: Color(0xFF1877F2),
    ),
    PlatformModel(
      name: 'X',
      url: 'https://x.com',
      icon: Icons.alternate_email,
      iconColor: Color(0xFF000000),
      category: 'social',
      backgroundColor: Color(0xFF1DA1F2),
    ),
    PlatformModel(
      name: 'Disney+',
      url: 'https://disneyplus.com',
      icon: Icons.movie_creation,
      iconColor: Color(0xFF113CCF),
      category: 'streaming',
      backgroundColor: Color(0xFF113CCF),
    ),
    PlatformModel(
      name: 'HBO Max',
      url: 'https://max.com',
      icon: Icons.live_tv,
      iconColor: Color(0xFF5822B4),
      category: 'streaming',
      backgroundColor: Color(0xFF5822B4),
    ),
    PlatformModel(
      name: 'Prime Video',
      url: 'https://primevideo.com',
      icon: Icons.ondemand_video,
      iconColor: Color(0xFF00A8E1),
      category: 'streaming',
      backgroundColor: Color(0xFF00A8E1),
    ),
    PlatformModel(
      name: 'Pinterest',
      url: 'https://pinterest.com',
      icon: Icons.image,
      iconColor: Color(0xFFBD081C),
      category: 'social',
      backgroundColor: Color(0xFFBD081C),
    ),
    PlatformModel(
      name: 'Quora',
      url: 'https://quora.com',
      icon: Icons.question_answer,
      iconColor: Color(0xFFB92B27),
      category: 'social',
      backgroundColor: Color(0xFFB92B27),
    ),
    PlatformModel(
      name: '9gag',
      url: 'https://9gag.com',
      icon: Icons.emoji_emotions,
      iconColor: Color(0xFF00B8FF),
      category: 'social',
      backgroundColor: Color(0xFF00B8FF),
    ),
    PlatformModel(
      name: 'iFunny',
      url: 'https://ifunny.co',
      icon: Icons.sentiment_satisfied_alt,
      iconColor: Color(0xFF3ECF8E),
      category: 'social',
      backgroundColor: Color(0xFF3ECF8E),
    ),
  ];
}
